naveditor.exe -console levels\mp_lobby.obj 1
naveditor.exe -console levels\mp_rr_aqueduct.obj 1
naveditor.exe -console levels\mp_rr_aqueduct_night.obj 1
naveditor.exe -console levels\mp_rr_arena_composite.obj 1
naveditor.exe -console levels\mp_rr_ashs_redemption.obj 1
naveditor.exe -console levels\mp_rr_canyonlands_64k_x_64k.obj 1
naveditor.exe -console levels\mp_rr_canyonlands_mu1.obj 1
naveditor.exe -console levels\mp_rr_canyonlands_mu1_night.obj 1
naveditor.exe -console levels\mp_rr_canyonlands_staging.obj 1
naveditor.exe -console levels\mp_rr_desertlands_64k_x_64k.obj 1
naveditor.exe -console levels\mp_rr_desertlands_64k_x_64k_nx.obj 1
naveditor.exe -console levels\mp_rr_desertlands_64k_x_64k_tt.obj 1
